version: "3.4"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    env_file:
      - ./.env
    ports:
      - 3000:3000
    networks:
      - dev
    command: npm run dev
  mongodb:
    container_name: app-database
    image: mongo
    command: mongod --auth
    environment:
      - MONGO_INITDB_DATABASE=my_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    restart: always 
    ports:
      - '27017:27017'
    networks:
      - dev

volumes:
  mongodb_data:
    driver: local

networks:
  dev:
    name: dev
    driver: bridge